### ISSUE TITLE
Error: Invalid explicit day of month definition

### ISSUE THREAD

**Issue by shvelo** [node-schedule/node-schedule#172]
I'm getting the following error when testing my application. I'm using nock for http mocking.

```
Error: Invalid explicit day of month definition
  at CronExpression._findSchedule (/foobar/node_modules/node-schedule/node_modules/cron-parser/lib/expression.js:388:15)
  at CronExpression.next (/foobar/node_modules/node-schedule/node_modules/cron-parser/lib/expression.js:455:23)
  at scheduleNextRecurrence (/foobar/node_modules/node-schedule/lib/schedule.js:433:90)
  at /foobar/node_modules/node-schedule/lib/schedule.js:392:19
  at callTimer (/foobar/node_modules/sinon/node_modules/lolex/src/lolex.js:216:24)
  at Object.tick (/foobar/node_modules/sinon/node_modules/lolex/src/lolex.js:368:21)
  at Context.<anonymous> (/foobar/test/unit/services/foobar.test.js:29:9)
  at Test.Runnable.run (/foobar/node_modules/mocha/lib/runnable.js:233:15)
  at Runner.runTest (/foobar/node_modules/mocha/lib/runner.js:390:10)
  at /foobar/node_modules/mocha/lib/runner.js:473:12
  at next (/foobar/node_modules/mocha/lib/runner.js:315:14)
  at /foobar/node_modules/mocha/lib/runner.js:325:7
  at next (/foobar/node_modules/mocha/lib/runner.js:260:23)
  at Immediate._onImmediate (/foobar/node_modules/mocha/lib/runner.js:292:5)
  at processImmediate [as _immediateCallback] (timers.js:358:17)
```

Test code: 
```javascript
var clock = sinon.useFakeTimers();
var scope = <nock mocks>;

schedule.scheduleJob("55 12 * * *", <callback function>);

clock.tick(<cron Date> - 1000);

setTimeout(function () {
	setTimeout(function() {
		assert.isTrue(scope.isDone(), "request sent");
		done();
	}, 1000);
	clock.tick(1000);
}, 1000);

clock.tick(1000);
```

**Comment by santigimeno** [comment]
@shvelo I can't reproduce it. Can you paste a complete sample I can execute that fails? Thanks!

**Comment by alexustinovsm** [comment]
+1
I have the same bug.

**Comment by alexustinovsm** [comment]
```
'use strict';

const schedule = require('node-schedule'),
      sh       = require('shelljs')

// sh.config.silent = true

const command = './my_script.sh'

schedule.scheduleJob('*/15 * * * *', function() {
    let cmd = sh.exec(command)
    if (cmd.code !== 0)
    {
        console.log(`Faild: ${cmd.output}`)
    }
    else
    {
        console.log(`\nSync is done`)    
    }
})
```

I use this code.

**Comment by wwgc** [comment]
+1

**Comment by MaFiaaaaAxD** [comment]
+1. I think error is associated with month change...

**Comment by Ilya-Starostin** [comment]
+1.. got the same bug today too.. exactly when date turned to Feb 01

**Comment by tejasmanohar** [comment]
see #225

**Comment by mohitkhanna** [comment]
+1 - life savior - thanks guys for reporting and fixing this. We've been struggling to get the RCA to one of our critical module crash due to this bug. This concludes my day at office... Phew! :-)
