### ISSUE TITLE
Strange behaviour when changing the date.

### ISSUE THREAD

**Issue by 4rzael** [node-schedule/node-schedule#208]
I experienced a strange behaviour (followed by a crash) when I change the date during the execution of the program.

Here's a little piece of code that reproduces the problem:

```js
var schedule = require('node-schedule');
var spawn = require('child_process').spawn;

function sleep() {
	return schedule.scheduleJob('00 00 * * *', function(){
		console.log("It's time to sleep !!!");
	});
}

function wakeUp() {
	return schedule.scheduleJob('00 08 * * *', function(){
		console.log("It's time to wake up !!!");
	});
}

var sleepJob = sleep();
var wakeJob = wakeUp();

setTimeout(function () {
	console.log('Changing the date');
	spawn('date', ['-s', '2015-11-10 07:59:45']);

	sleepJob.cancel();
	sleepJob = sleep();

	wakeJob.cancel();
	wakeJob = wakeUp();

}, 10000);
```

I start this code using this line: 

```sh
date -s '1970-01-01 16:00:00'; node schedule.js
```

And I get something like this (in less than 1 second after the `setTimeout`)

```
It's time to wake up !!!
It's time to wake up !!!
It's time to wake up !!!
...
It's time to wake up !!!
It's time to wake up !!!
It's time to wake up !!!
It's time to wake up !!!
It's time to wake up !!!
It's time to wake up !!!
It's time to wake up !!!
It's time to wake up !!!
It's time to wake up !!!
It's time to wake up !!!
It's time to wake up !!!
It's time to wake up !!!
It's time to wake up !!!
It's time to wake up !!!
It's time to wake up !!!
It's time to wake up !!!
It's time to wake up !!!
It's time to wake up !!!
It's time to wake up !!!
/root/scheduler/node_modules/node-schedule/node_modules/cron-parser/lib/expression.js:388
        throw new Error('Invalid explicit day of month definition');
        ^
Error: Invalid explicit day of month definition
    at CronExpression._findSchedule (/root/scheduler/node_modules/node-schedule/node_modules/cron-parser/lib/expression.js:388:15)
    at CronExpression.next (/root/scheduler/node_modules/node-schedule/node_modules/cron-parser/lib/expression.js:455:23)
    at scheduleNextRecurrence (/root/scheduler/node_modules/node-schedule/lib/schedule.js:434:90)
    at /root/scheduler/node_modules/node-schedule/lib/schedule.js:393:19
    at process._tickCallback (node.js:355:11)
```

#### Note:

I'm using node v0.10.40 and node-schedule v0.3.0

**Comment by santigimeno** [comment]
@4rzael Moving the `cancel`'s before changing the date fixes the issue

**Comment by 4rzael** [comment]
@santigimeno Yes, it does. Thanks !

**Comment by 4rzael** [comment]
Just a question: Do you know what created this behaviour, and how to avoid it in the future ? Also, is it going to be fixed ?

**Comment by santigimeno** [comment]
I guess it's not good idea to change the system date while there are JS timeouts running. It's probable that bad things are going to happen. That's why I suggested that change: cancel the jobs / timeouts and then change the system date.
I'm not sure there's something to be fixed

**Comment by 4rzael** [comment]
Okay, thanks for the information !
