### ISSUE TITLE
Invalid explicit day of month definition 

### ISSUE THREAD

**Issue by corbanb** [node-schedule/node-schedule#237]
Hi all,

Last night I had a error that has never happened to our app. Its been running for about 7 months now and I would of expected to have seen this due to it have been the 31st a few times. But some how last night a job failed due to `uncaughtException: Invalid explicit day of month definition`

Has anyone seen this before? 

```
Jan 30 16:30:00 my-app app/worker.1:  error: uncaughtException: Invalid explicit day of month definition date=Sun Jan 31 2016 00:30:00 GMT+0000 (UTC), pid=3, uid=40215, gid=40215, cwd=/app, execPath=/app/.heroku/node/bin/node, version=v0.12.9, argv=[node, /app/worker.js], rss=164454400, heapTotal=119434496, heapUsed=83217216, loadavg=[2.78564453125, 4.24658203125, 4.8505859375], uptime=73765 
Jan 30 16:30:00 my-app app/worker.1:  Error: Invalid explicit day of month definition 
Jan 30 16:30:00 my-app app/worker.1:  ,    at CronExpression._findSchedule (/app/node_modules/node-schedule/node_modules/cron-parser/lib/expression.js:388:15) 
Jan 30 16:30:00 my-app app/worker.1:  ,    at CronExpression.next (/app/node_modules/node-schedule/node_modules/cron-parser/lib/expression.js:455:23) 
Jan 30 16:30:00 my-app app/worker.1:  ,    at scheduleNextRecurrence (/app/node_modules/node-schedule/lib/schedule.js:433:90) 
Jan 30 16:30:00 my-app app/worker.1:  ,    at null._onTimeout (/app/node_modules/node-schedule/lib/schedule.js:392:19) 
Jan 30 16:30:00 my-app app/worker.1:  ,    at Timer.listOnTimeout (timers.js:119:15) 
Jan 30 16:30:00 my-app app/worker.1:  error: uncaughtException: Invalid explicit day of month definition date=Sun Jan 31 2016 00:30:00 GMT+0000 (UTC), pid=3, uid=40215, gid=40215, cwd=/app, execPath=/app/.heroku/node/bin/node, version=v0.12.9, argv=[node, /app/worker.js], rss=164454400, heapTotal=119434496, heapUsed=83504104, loadavg=[2.78564453125, 4.24658203125, 4.8505859375], uptime=73765 
```

**Comment by corbanb** [comment]
If it help's its happening all day today now also I just realized.

Here is how I am setting the job's

```
var startMinute = 30;
var startHour = 11;
schedule.scheduleJob(startMinute + ' ' + startHour + ' * * *', function() { abe.jobs.trigger.job('start', 'west'); });
```

I am not sure why it would complain about the day of the month when I am running * as the day. Thoughts?

**Comment by albertdatui** [comment]
Hi,

see this issue, #225

**Comment by tejasmanohar** [comment]
dupe
