### ISSUE TITLE
Error: Invalid explicit day of month definition

### ISSUE THREAD

**Issue by slavafomin** [node-schedule/node-schedule#238]
Hello!

I'm using the following code:

```javascript
schedule.scheduleJob('45 19 * * *', function () {
  console.log('RUNNING JOB');
});
```

And getting the following error at the specified time:

```
/app/node_modules/cron-parser/lib/expression.js:388
        throw new Error('Invalid explicit day of month definition');
        ^

Error: Invalid explicit day of month definition
    at CronExpression._findSchedule (/app/node_modules/cron-parser/lib/expression.js:388:15)
    at CronExpression.next (/app/node_modules/cron-parser/lib/expression.js:455:23)
    at scheduleNextRecurrence (/app/node_modules/node-schedule/lib/schedule.js:449:90)
    at null._onTimeout (/app/node_modules/node-schedule/lib/schedule.js:408:19)
    at Timer.listOnTimeout (timers.js:92:15)
```

What could be the reason for this?

**Comment by albertdatui** [comment]
Hi,

There is an issue for this. you can check it out #225

**Comment by tejasmanohar** [comment]
dupe
