### ISSUE TITLE
Cron doesn't run the jobs since 31.01.16 00:00:00

### ISSUE THREAD

**Issue by ekussberg** [node-schedule/node-schedule#241]
Hello guys,

we have a problem, that our cronjobs don't run anymore and the last error we got was:

'''
2016-01-31T22:30:00.257302384Z /app/node_modules/node-schedule/node_modules/cron-parser/lib/expression.js:388
2016-01-31T22:30:00.257408837Z         throw new Error('Invalid explicit day of month definition');
2016-01-31T22:30:00.257425499Z               ^
2016-01-31T22:30:00.257435586Z Error: Invalid explicit day of month definition
2016-01-31T22:30:00.257446143Z     at CronExpression._findSchedule (/app/node_modules/node-schedule/node_modules/cron-parser/lib/expression.js:388:15)
2016-01-31T22:30:00.257456350Z     at CronExpression.next (/app/node_modules/node-schedule/node_modules/cron-parser/lib/expression.js:455:23)
2016-01-31T22:30:00.257467123Z     at scheduleNextRecurrence (/app/node_modules/node-schedule/lib/schedule.js:433:90)
2016-01-31T22:30:00.257477829Z     at /app/node_modules/node-schedule/lib/schedule.js:392:19
2016-01-31T22:30:00.257487130Z     at /app/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
2016-01-31T22:30:00.257496724Z     at process._tickDomainCallback (node.js:381:11)
2016-01-31T22:30:00.257506122Z     at process.wrappedFunction (/app/node_modules/newrelic/lib/transaction/tracer/index.js:245:51)
2016-01-31T22:30:00.257517448Z     at process.<anonymous> (/app/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:19:15)
'''

Does anybody know what can be an issue?

**Comment by santigimeno** [comment]
Dup of https://github.com/node-schedule/node-schedule/issues/225
