### ISSUE TITLE
Mass deletion of scheduled jobs stops new schedules being created

### ISSUE THREAD

**Issue by geocontrol** [node-schedule/node-schedule#262]
Hi,

I create schedules with the following code:

```
var job = schedule.scheduleJob(schedUName, scheduletime, function() {
			// Trigger the SMS messge
			triggerSMS(messageSchedule.messageId, messageSchedule.userId, model.id);
		});
```

And remove them with 

```
var jobs = schedule.scheduledJobs;
	
	console.log(JSON.stringify(jobs));
	
	var killJob = jobs[identPrefix + scheduleID];
	
	if (killJob) {
		killJob.cancel();
		console.log("Scedule removed");
	    res.status(200);
	    res.json({
	    	"status": 200,
			"message": "Prompt Submitted for Deletion"
	    });
	} else {
		console.log("The Schedule to be terminated does not exist: " + identPrefix + scheduleID);
        res.status(500);
        res.json({
        	"status": 500,
			"message": "Error getting the message"
        });
	};
```

But when I do a mass deletion:

```
new Model.Message().query({where: {id: message_id}}).fetch({withRelated: ['schedule', 'repeatschedule']}).then(function(message){
			// Gets the message record with all the releated schedules and repeatSchedules
			var JSONmessage = message.toJSON(); 
			console.log('=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=');
			console.log('Message Record: ' + JSONmessage);
			
			var theMessage = JSONmessage;
			var schedules = JSONmessage.schedule;
			
			for (schedule in schedules) {
				console.log('The Schedule Data is : ' + JSONmessage.schedule[schedule].id);
				new Model.Schedule({id: JSONmessage.schedule[schedule].id}).destroy();
				killJob = jobs["Sched" + JSONmessage.schedule[schedule].id];
	
				if (killJob) {
					killJob.cancel();
					console.log("Scedule removed");
				} else {
					console.log("The Schedule to be terminated does not exist: Sched" + JSONmessage.schedule[schedule].id);
				};
			};
```

And then try and create a new schedule for a new message, i get the following error messgae:

Unhandled rejection TypeError: undefined is not a function
    at null.<anonymous> (/Users/mark/Code/zzWork/AlwaysListening/alclient/api.js:254:22)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
From previous event:
    at scheduleMessage (/Users/mark/Code/zzWork/AlwaysListening/alclient/api.js:250:21)
    at Layer.handle [as handle_request] (/Users/mark/Code/zzWork/AlwaysListening/alclient/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/mark/Code/zzWork/AlwaysListening/alclient/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/Users/mark/Code/zzWork/AlwaysListening/alclient/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/Users/mark/Code/zzWork/AlwaysListening/alclient/node_modules/express/lib/router/layer.js:82:5)
    at /Users/mark/Code/zzWork/AlwaysListening/alclient/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/Users/mark/Code/zzWork/AlwaysListening/alclient/node_modules/express/lib/router/index.js:321:12)
    at next (/Users/mark/Code/zzWork/AlwaysListening/alclient/node_modules/express/lib/router/index.js:261:10)
    at SessionStrategy.strategy.pass (/Users/mark/Code/zzWork/AlwaysListening/alclient/node_modules/passport/lib/middleware/authenticate.js:318:9)
    at SessionStrategy.authenticate (/Users/mark/Code/zzWork/AlwaysListening/alclient/node_modules/passport/lib/strategies/session.js:67:10)
    at attempt (/Users/mark/Code/zzWork/AlwaysListening/alclient/node_modules/passport/lib/middleware/authenticate.js:341:16)
    at authenticate (/Users/mark/Code/zzWork/AlwaysListening/alclient/node_modules/passport/lib/middleware/authenticate.js:342:7)
    at Layer.handle [as handle_request] (/Users/mark/Code/zzWork/AlwaysListening/alclient/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/Users/mark/Code/zzWork/AlwaysListening/alclient/node_modules/express/lib/router/index.js:302:13)
    at /Users/mark/Code/zzWork/AlwaysListening/alclient/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/Users/mark/Code/zzWork/AlwaysListening/alclient/node_modules/express/lib/router/index.js:321:12)
    at next (/Users/mark/Code/zzWork/AlwaysListening/alclient/node_modules/express/lib/router/index.js:261:10)
    at initialize (/Users/mark/Code/zzWork/AlwaysListening/alclient/node_modules/passport/lib/middleware/initialize.js:62:5)
    at Layer.handle [as handle_request] (/Users/mark/Code/zzWork/AlwaysListening/alclient/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/Users/mark/Code/zzWork/AlwaysListening/alclient/node_modules/express/lib/router/index.js:302:13)
    at /Users/mark/Code/zzWork/AlwaysListening/alclient/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/Users/mark/Code/zzWork/AlwaysListening/alclient/node_modules/express/lib/router/index.js:321:12)
    at next (/Users/mark/Code/zzWork/AlwaysListening/alclient/node_modules/express/lib/router/index.js:261:10)
    at Immediate.<anonymous> (/Users/mark/Code/zzWork/AlwaysListening/alclient/node_modules/express-session/index.js:433:7)
    at Immediate.immediate._onImmediate (timers.js:418:16)

I.e. it all works fine until I do a mass deletion (in the app, you delete a message which could have a number of schedules attached to it, so we go through all the schedules and kill them.)

Any idea why? It is version 1.0 of node-schedule i have installed as well.

Thanks

Mark

**Comment by santigimeno** [comment]
@geocontrol From the stack trace you posted, I can't see anything directly related with `node-schedule`. Would it possible for you to create a simple self contained program that reproduces the problem? Thanks

**Comment by geocontrol** [comment]
No, you are right looking at it, i took out the call to cancel the jobs and it gives the same message, so it must be elsewhere in the model / database ?

I'll try and filter it all out

**Comment by santigimeno** [comment]
Closing this. @geocontrol feel free to reopen if it's still an issue. Thanks
