### ISSUE TITLE
 Cannot read property 'execute' of undefined

### ISSUE THREAD

**Issue by qiufeihong2018** [node-schedule/node-schedule#509]
`    this.job.execute(fireDate);              ^  TypeError: Cannot read property 'execute' of undefined`

**Comment by FutureKen** [comment]
Having the same issue after upgrading to NodeJS v10 (v10.16.3)
`TypeError: Cannot read property 'execute' of undefined
    at Job.invoke (/xxx/node_modules/node-schedule/lib/schedule.js:175:14)
    at Timeout._onTimeout (/xxx/node_modules/node-schedule/lib/schedule.js:543:11)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)`
