### ISSUE TITLE
TypeError: this.job.execute is not a function

### ISSUE THREAD

**Issue by Liyoh** [node-schedule/node-schedule#515]
我把任务计划保存到了数据库里，我想在服务器启动时候，就默认执行初始化的方法，该方法可以从数据库中查询很多的任务，同时要把这些任务开启。
````
executeSchedule: async function (scheduleId) {
            const s = await this.findOne({ _id: scheduleId })
            const scheduleJobObj = await schedule.scheduleJob(scheduleId, s.cron, () => { console.log('scheduleId', scheduleId) })
            return scheduleJobObj
        },
initSchedule: async function () {
            const schedule_list = await this.find({ isCancel: false })
            const job = await Promise.all(schedule_list.map(async (s) => {
                return await this.executeSchedule(s._id)
            }))
            console.log(job)
            return job
        }
````

值得注意的是：executeSchedule函数中 `schedule.scheduleJob` **第三个参数确实是callback，当我调用executeSchedule单独运行一个任务的时候，它却可以，而当我使用initSchedule函数使用map函数开启多个任务的时候，它就报错了**

Error info:
````
服务器启动中.. 正在初始化用户的计划任务...
Mongoose Connect Success!
[ Job {
    job: '* * * * * *',
    callback: [Function],
    name: '<Anonymous Job 1>',
    trackInvocation: [Function],
    stopTrackingInvocation: [Function],
    triggeredJobs: [Function],
    setTriggeredJobs: [Function],
    cancel: [Function],
    cancelNext: [Function],
    reschedule: [Function],
    nextInvocation: [Function],
    pendingInvocations: [Function] } ]




scheduleId 5dc536ace1dcb60deabb98f3

/Users/frank/Documents/WorkProject/tongxi/afu_operation/schedule/node_modules/node-schedule/lib/schedule.js:175
    this.job.execute(fireDate);
             ^
TypeError: this.job.execute is not a function
    at Job.invoke (/Users/frank/Documents/WorkProject/tongxi/afu_operation/schedule/node_modules/node-schedule/lib/schedule.js:175:14)
    at /Users/frank/Documents/WorkProject/tongxi/afu_operation/schedule/node_modules/node-schedule/lib/schedule.js:552:11
    at Timeout._onTimeout (/Users/frank/Documents/WorkProject/tongxi/afu_operation/schedule/node_modules/node-schedule/lib/schedule.js:510:7)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
````

**Comment by Liyoh** [comment]
问题得到了解决，如果您在项目中使用MongoDB，那么请注意，使用id作为任务的唯一值，则需要注意类型问题，即
````
 return await this.executeSchedule(s._id)
````
改为
````
 return await this.executeSchedule(s._id+'')
````
