### ISSUE TITLE
Installing won't work on RPi

### ISSUE THREAD

**Issue by quintendewilde** [node-schedule/node-schedule#527]
I'm trying to install this. 
But I get this error log.
```

root@raspberrypi:/home/pi/Tools-for-Instagram/bots# npm install node-schedule

> canvas@2.6.1 install /home/pi/Tools-for-Instagram/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v83-linux-glibc-arm.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@14.2.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
gyp WARN EACCES current user ("pi") does not have permission to access the dev dir "/root/.cache/node-gyp/14.2.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/Tools-for-Instagram/node_modules/canvas/.node-gyp"
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.19.97-v7l+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/Tools-for-Instagram/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/pi/Tools-for-Instagram/node_modules/canvas/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /home/pi/Tools-for-Instagram/node_modules/canvas
gyp ERR! node -v v14.2.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/Tools-for-Instagram/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/pi/Tools-for-Instagram/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/Tools-for-Instagram/node_modules/canvas/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Linux 4.19.97-v7l+
node-pre-gyp ERR! command "/usr/bin/node" "/home/pi/Tools-for-Instagram/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/Tools-for-Instagram/node_modules/canvas
node-pre-gyp ERR! node -v v14.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/Tools-for-Instagram/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/pi/Tools-for-Instagram/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN @tensorflow/tfjs-converter@1.5.2 requires a peer of @tensorflow/tfjs-core@1.5.2 but none is installed. You must install peer dependencies yourself.
npm WARN @tensorflow/tfjs-data@1.5.2 requires a peer of @tensorflow/tfjs-core@1.5.2 but none is installed. You must install peer dependencies yourself.
npm WARN @tensorflow/tfjs-layers@1.5.2 requires a peer of @tensorflow/tfjs-core@1.5.2 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-12T12_47_20_153Z-debug.log
```

**Comment by quintendewilde** [comment]
anybody??

**Comment by jasonappah** [comment]
I'm honestly not sure, but this might be a problem??
```
gyp WARN EACCES current user ("pi") does not have permission to access the dev dir "/root/.cache/node-gyp/14.2.0"
```

**Comment by Mrebai** [comment]
I fixed it by downgrading node from the current version (14.3.0) to the LTS version (12.17.0)
