### ISSUE TITLE
Cannot read property 'execute' of undefined

### ISSUE THREAD

**Issue by VeeneN** [node-schedule/node-schedule#556]
I have one little problem with my code;

My code: commands.js
module.exports.execute= {
    name: 'commands',
    description: "Embed!",
    execute(message, args, Discord){
        const newEmbed = new Discord.MessageEmbed()
        .setColor('#9932cc')
        .setTitle('Kurallar')
        .setURL('https://discord.gg/mfNmCuqbvT')
        .setDescription('Aramıza hoş geldiniz! Bu discord sunucusu Aschenteoğulları sunucusudur.')
        .addFields(
            {name:'Genel kurallar:', value:':hype:  Kışkırtıcı kelime kullanmak veya karşı tarafa saldırgan nitelikte söylemlerde bulunmak yasaktır.}'},
        )
        .setImage('https://cdn.discordapp.com/attachments/798645928332492811/798966738930368532/Aschente_2.jpg')
        .setFooter('Aschente Moderasyon iyi günler diler!');

        message.channel.send(newEmbed);
    }
}

My code; main.js
const Discord = require('discord.js');
const { FILE } = require('dns');
const client = new Discord.Client();

const prefix ='!';

const fs = require('fs');
const { fileURLToPath } = require('url');

client.commands = new Discord.Collection();

const commandsFiles = fs.readdirSync('./commands/').filter(ƒile => ƒile.endsWith('.js'));
for(const file of commandsFiles){
    const command = require(`./commands/${file}`);
    client.commands.set(command.name, command);
}

client.once ('ready', () => {

    console.log('Aschente burada');
});

client.on('message' , message => {
    if(!message.content.startsWith(prefix) || message.author.bot) return;

    const args = message.content.slice(prefix.length).split(/ +/);
    const command = args.shift().toLowerCase();

    if(command === 'ping'){
     client.commands.get('ping').execute(message, args);
    } else if(command === 'davet'){
        client.commands.get('davet').execute(message, args);
    } else if(command === 'kayıt'){
        client.commands.get('kayıt').execute(message, args);    
    } else if(command === 'siyaset'){
        client.commands.get('siyaset').execute(message, args);
    } else if(command === 'oyun'){
        client.commands.get('oyun').execute(message, args);
    }else if(command === 'kumarhane'){
        client.commands.get('kumarhane').execute(message, args);
    }else if(command === 'nsfw'){
        client.commands.get('nsfw').execute(message, args);
    }else if(command === 'commands'){
        client.commands.get('commands').execute(message, args, Discord);
    }
    
    
    
 });

client.login ('XXXXX');

And my error;TypeError: Cannot read property 'execute' of undefined
    at Client.<anonymous> (/Users/kaandenizyeklitas/Documents/GitHub/Aschente/main.js:45:40)
    at Client.emit (events.js:315:20)

**Comment by danshilm** [comment]
This is not a node-schedule bug.

Check out the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_access_property) about this.
