### ISSUE TITLE
node-schedule Error: CronDate: unhandled timestamp:1659539835855

### ISSUE THREAD

**Issue by pradeeppal2677** [node-schedule/node-schedule#690]
we have facing issue Error: CronDate: unhandled timestamp:1659539835855 I have not idea which reason i will getting this error
**roundUpCron/scheduleNotification Error: CronDate: unhandled timestamp: 1659539835855
    at new CronDate (/app/node_modules/cron-parser/lib/date.js:233:11)
    at RecurrenceRule._nextInvocationDate (/app/node_modules/node-schedule/lib/Invocation.js:137:15)
    at scheduleNextRecurrence (/app/node_modules/node-schedule/lib/Invocation.js:324:56)
    at Job.schedule (/app/node_modules/node-schedule/lib/Job.js:266:13)
    at Object.scheduleJob (/app/node_modules/node-schedule/lib/schedule.js:39:11)
    at Object.roundUpCron.scheduleNotification (/app/modules/v1/cron/roundUpCron.js:76:34)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)**

**Comment by PayalChhugani** [comment]
Above same issue we are facing, Can someone help us in this case as soon as possible?

**Comment by yorch** [comment]
Most likely you have an error in the timezone name you are using, check the list of supported TZs here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
